[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"
  directory = ".output/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = ".output/public"

[context.deploy-preview]
  command = "npm run build"
  publish = ".output/public"

[context.branch-deploy]
  command = "npm run build"
  publish = ".output/public"
